export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";

export const UPDATE_RESOURCE_MODAL_OPENED = "MODAL_OPENED";
export const UPDATE_RESOURCE_MODAL_CLOSED = "MODAL_CLOSED";
